### ISSUE TITLE
Improvement for 2_efectos_arreglos_texto/ESCENAS.md

### ISSUE THREAD

**Issue by quark67** [Elteoremadebeethoven/AnimacionesConManim#1]
(I have previously send to you an email a week ago, but you don't seem to read it. Is your public gmail address valid?)

In https://github.com/Elteoremadebeethoven/AnimacionesConManim/blob/master/Español/2_efectos_arreglos_texto/ESCENAS.md, 
I see the code :

```python
class ColorPorCaracter(Scene):
	def construct(self):
		texto = TexMobject("{d","\\over","d","x","}","\\int_","{a}^","{","x","}","f(","t",")d","t","=","f(","x",")")
		texto.set_color_by_tex("x",RED)
		self.play(Write(texto))
		self.wait(2)
```

which produce this:
![image](https://user-images.githubusercontent.com/9338576/51431363-0a626180-1c28-11e9-937c-5ff4a4cd123d.png)

Strangely, "a" is in red. Is this a bug?

If you invert upper and lower limit position of the integral sign (\int^x_a instead of \int_a^x), the bug vanish. Try this:

```python
texto = TexMobject("d","\\over","d","x","}","\\int^","{","x","}_","a","f(","t",")d","t","=","f(","x",")")
```

I obtain:
![image](https://user-images.githubusercontent.com/9338576/51431373-1bab6e00-1c28-11e9-846b-2a63c4f56940.png)

Anyway, I think there is a bug in manim. Should we fill a bug report about this? (I'm beginner with manim, as you already saw with my question https://github.com/3b1b/manim/issues/373).

**Comment by Elteoremadebeethoven** [comment]
Sorry, I'm busy right now but, if you wanna you can report this. I think it is not a big deal, you can solve with a little tricks with latex like you saw.
