### ISSUE TITLE
Problema con Pycairo para Manim

### ISSUE THREAD

**Issue by RubenCedillo123** [Elteoremadebeethoven/AnimacionesConManim#4]
Hola, no tengo ninguna experiencia programando. Este es el problema que tengo a la hora de finalizar la instalación de Manim.
![LTX](https://user-images.githubusercontent.com/78295573/106378206-93a8e480-6368-11eb-9f27-9e59bb510abf.png)

**Comment by RubenCedillo123** [comment]
Actualmente me encuentro reinstalando todo, pero no hay ningún cambio.

**Comment by Elteoremadebeethoven** [comment]
Busca el error en Google, no instalaste correctamente las dependencias (via PIP), hay mucha información en internet, así que no daré más detalles.
